---
# you can use glob pattern

# You can set multiple reviewers
# '.github/':
#   - yikeke
#   - ran-huang

# 'tiflash/':
#   - zanmato1984
#   - kissmydb
#   - yikeke

# 'tiup/':
#   - lonng
#   - lucklove
#   - kissmydb
#   - yikeke

# 'sql-statements/':
#   - bb7133

# 'releases/':
#   - scsldb

# 'dashboard/':
#   - breeswish

# 'config-templates/':
#   - kissmydb

# 'ticdc/':
#   - WangXiangUSTC

# Changing all md files should request a language review in case of format failures.
# TomShawn is the repo administrator.
'*.*':
  - TomShawn
