---
# Changing all md files should request a language review in case of format failures.
# TomShawn is the repo administrator.
'**/*':
  - TomShawn

# you can use glob pattern

# You can set multiple reviewers
'.github/':
  - yikeke
  - ran-huang

'tiflash/':
  - ilovesoup
  - zanmato1984
  - kissmydb
  - yikeke

'tiup/':
  - lonng
  - lucklove
  - kissmydb
  - yikeke

'sql-statements/':
  - bb7133
  - zimulala

'releases/':
  - scsldb
  - uglyengineer

'dashboard/':
  - breeswish
  - hundundm

'config-templates/':
  - kissmydb
  - superlzs0476

'ticdc/':
  - WangXiangUSTC
  - 3pointer
