---
# Changing all md files should request a language review in case of format failures.
# TomShawn is the repo administrator.

# you can use glob pattern

# You can set multiple reviewers
'.github/**/*.yml':
  - yikeke
  - ran-huang

'tiflash/**/*.md':
  - ilovesoup
  - zanmato1984
  - kissmydb
  - yikeke

'tiup/**/*.md':
  - lonng
  - lucklove
  - kissmydb
  - yikeke

'sql-statements/**/*.md':
  - bb7133
  - zimulala

'releases/**/*.md':
  - scsldb
  - uglyengineer

'dashboard/**/*.md':
  - breeswish
  - hundundm

'config-templates/**/*.yaml':
  - kissmydb
  - superlzs0476

'ticdc/**/*.md':
  - WangXiangUSTC
  - 3pointer

'**/*':
  - TomShawn
