---
# Changing all md files should request a language review in case of format failures.
# TomShawn is the repo administrator.

# you can use glob pattern

# You can set multiple reviewers
'.github/**/*.yml':
  - yikeke
  - ran-huang

# 'benchmark/**/*.md':
#   - jackysp
#   - kissmydb
#   - TomShawn

'best-practices/**/*.md':
  - kissmydb
  - lilin90
  - TomShawn

'br/**/*.md':
  - kissmydb
  - WangXiangUSTC
  - TomShawn

'config-templates/**/*.yaml':
  - kissmydb
  - superlzs0476
  - TomShawn

'dashboard/**/*.md':
  - breeswish
  - hundundm
  - kissmydb
  - TomShawn

'faq/**/*.md':
  - kissmydb
  - TomShawn

# 'functions-and-operators/**/*.md':
#   - kissmydb
#   - TomShawn

# 'media/**/*':
#   - TomShawn
#   - lilin90

'releases/**/*.md':
  - scsldb
  - uglyengineer
  - TomShawn

'resources/**/*':
  - yikeke
  - lilin90

'scripts/**/*':
  - yikeke
  - lilin90

'sql-statements/**/*.md':
  - bb7133
  - zimulala
  - TomShawn

# 'storage-engine/**/*.md':
#   - TomShawn
#   - 

# 'sync-diff-inspector/**/*.md':
#   - TomShawn
#   - 

# 'system-tables/**/*.md':
#   - TomShawn
#   - 

'ticdc/**/*.md':
  - WangXiangUSTC
  - 3pointer
  - kissmydb
  - TomShawn

'tidb-binlog/**/*.md':
  - july2993
  - kissmydb
  - TomShawn

'tidb-lightning/**/*.md':
  - WangXiangUSTC
  - kissmydb
  - TomShawn

'tiflash/**/*.md':
  - ilovesoup
  - zanmato1984
  - kissmydb
  - yikeke

'tiup/**/*.md':
  - lonng
  - lucklove
  - kissmydb
  - yikeke

# All other file pattern will match the following:

'**/*':
  - TomShawn
