comment: 'Rules for PingCAP docs-cn'

# disable all by default
default: false

# MD001
heading-increment: true

# MD003
heading-style:
  style: atx

# MD009
no-trailing-spaces: true

# MD010
no-hard-tabs: true

# MD007
ul-indent:
  indent: 4

# MD012
no-multiple-blanks: true

# commands-show-output: true

# MD018
no-missing-space-atx: true

# MD019
no-multiple-space-atx: true

# MD022
blanks-around-headings: true

# MD023
heading-start-left: true

# MD024
no-duplicate-heading:
  siblings_only: true

# MD025
single-title:
  front_matter_title: ''

# MD026
no-trailing-punctuation:
  punctuation: '.,;:!。，；：！'

# MD027
no-multiple-space-blockquote: true

# MD029
ol-prefix:
  style: ordered

# MD030
list-marker-space: true

# MD031
blanks-around-fences: true

# MD032
blanks-around-lists: true

# MD034
no-bare-urls: true

# MD037
no-space-in-emphasis: true

# MD038
no-space-in-code: true

# MD039
no-space-in-links: true

# MD042
no-empty-links: true

# proper-names:
#   names: ['TiDB', 'TiKV', 'PingCAP']
#   code_blocks: false

# MD045
no-alt-text: true

# MD046
code-block-style:
  style: fenced

# single-trailing-newline: true

# MD041
first-line-heading: true
