global:
  user: "tidb"
  group: "tidb"
  ssh_port: 22
  deploy_dir: "/em-deploy"
  data_dir: "/em-data"
  arch: "amd64"
  log_level: "info"
  # specify the external elasticsearch address. default is empty
  # and elasticsearch_servers can only have one value
  external_elasticsearch_url: ""
  login_host_user: ""
  login_private_key_path: ""
  login_public_key_path: ""

monitored:
  node_exporter_port: 4124

em_cluster_servers:
  - host: {ip}
  # port: 4101
  # metrics_port: 4104
  # registry_client_port: 4106
  # registry_peer_port: 4107
  # deploy_dir: "/em-deploy/cluster-server-4101"
  # data_dir: "/em-data/cluster-server-41101"

em_api_servers:
  - host: {ip}
  # port: 4100
  # metrics_port: 4103
  # deploy_dir: "/em-deploy/openapi-server-4100"
  # data_dir: "/em-data/openapi-server-4100"

em_web_servers:
  - host: {ip}
  # port: 4180
  # deploy_dir: "/em-deploy/em-web-4180"
  # data_dir: "/em-data/em-web-4180"

em_file_servers:
  - host: {ip}
  # port: 4102
  # metrics_port: 4105
  # deploy_dir: "/em-deploy/file-server-4102"
  # data_dir: "/em-data/file-server-4102"

elasticsearch_servers:
  - host: {ip}
  # port: 4108
  # heap_size: "4g"
  # deploy_dir: "/em-deploy/elasticsearch-4108"
  # data_dir: "/em-data/elasticsearch-4108"

tracer_servers:
  - host: {ip}
  # port: 4114
  # web_port: 4115
  # zipkin_thrift_port: 4116
  # compact_thrift_port: 4117
  # binary_thrift_port: 4118
  # agent_serve_port: 4119
  # jaeger_thrift_port: 4120
  # jaeger_host_port: 4121
  # collector_port: 4122
  # grpc_serve_port: 4123
  # deploy_dir: "/em-deploy/tracer-4114"
  # data_dir: "/em-data/tracer-4114"

kibana_servers:
  - host: {ip}
  # port: 4109
  # deploy_dir: "/em-deploy/kibana-4109"
  # data_dir: "/em-data/kibana-4109"

monitoring_servers:
  - host: {ip}
  # port: 4110
  # deploy_dir: "/em-deploy/prometheus-4110"
  # data_dir: "/em-data/prometheus-4110"

alertmanager_servers:
  - host: {ip}
  # web_port: 4112
  # cluster_port: 4113
  # deploy_dir: "/em-deploy/alertmanager-4112"
  # data_dir: "/em-data/alertmanager-4112"

grafana_servers:
  - host: {ip}
  # port: 4111
  # deploy_dir: "/em-deploy/grafana-4111"
  # data_dir: "/em-data/grafana-4111"

filebeat_servers:
  - host: {ip}
  # deploy_dir: "/em-deploy/filebeat-0"
  # data_dir: "/em-data/filebeat-0"
