name: Auto Assign to Project

on:
  issue:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Docs SIG Project
    steps:
    - name: Assign NEW issues to Docs SIG project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/pingcap/docs-cn/projects/1'
        column_name: 'Issue: Backlog'
