name: Flush PDF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  flush-pdf:
    name: Flush PDF
    runs-on: ubuntu-latest
    steps:
      - name: install qiniu qshell
        uses: foxundermoon/setup-qshell@v5
        with:
          version: '2.6.2'

      - name: Download PDF list
        run: |
          curl https://raw.githubusercontent.com/pingcap/docs-cn/master/resources/cdnfresh.txt --output cdnfresh.txt
          cat cdnfresh.txt

      - name: refresh url
        run: |
          qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} tidb
          qshell cdnrefresh -i cdnfresh.txt
