name: Keywords

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  check-keywords:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          ./scripts/check-keywords.py \
          --download_from_url \
          --parser_url https://github.com/pingcap/tidb/raw/refs/heads/${GITHUB_BASE_REF}/pkg/parser/parser.y
