name: Report 404 links

on:
  push:
    branches:
      - master
  schedule:
    # Run at 12:00 in working days
    - cron: 0 12 * * 0-5

jobs:
  build:
    name: Validate links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Validate links
      uses: ad-m/report-link-action@master
      with:
        github_token: ${{ secrets.roedeercuco }}