name: "Close stale issues/prs"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 60 days with no activity. If no comment has been made and the `lifecycle/stale` label is not removed, this issue will be closed in 15 days.'
        close-issue-message: 'This issue will be closed because it has been stale for 15 days with no activity. If you still have any question about this issue, feel free to reopen it or create a new one.'
        days-before-stale: 60
        days-before-close: 15
        stale-issue-label: 'lifecycle/stale'
        exempt-issue-labels: 'lifecycle/frozen,good-first-issue,help-wanted'
