name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.roedeercuco }}
        stale-issue-message: 'This is a stale issue message.'
        stale-pr-message: 'This is a stale pull request message.'
        stale-issue-label: 'action/no-issue-activity'
        stale-pr-label: 'action/no-pr-activity'