name: Translation Welcome

on:
  issues:
    types: [unlabeled, labeled]
  pull_request:
    types: [unlabeled, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Auto Add to Project
    steps:
    - name: Add translation-welcome PRs/Issues to Project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'translation/welcome') ||
        contains(github.event.pull_request.labels.*.name, 'translation/welcome')
      with:
        project: 'https://github.com/pingcap/docs-cn/projects/2'
        column_name: 'To do'
